name = "VET_Unflipping"
modname = "vet_unflipping"
prefix = "vet"
author = "veteran29"
version = "1.3.0"
files = ["mod.cpp"]

keyname = "{{prefix}}_unflipping_{{version}}"
signame = "{{prefix}}_unflipping_{{version}}"
reuse_private_key = true

releasebuild = [
    "!Set_version",
    "@zip",
    "!publish"
]

[scripts]
    [scripts.Set_version]
        steps_windows = [
            "powershell ./tools/Set-Version.ps1 {{version}}"
        ]
        # show_output = true

    [scripts.publish]
        steps_windows = [
            "powershell ./tools/Publish.ps1 {{version}} 1703187116 '@{{name}}'"
        ]
        show_output = true
